### ISSUE TITLE
camelCase inconsistent with lodash

### ISSUE THREAD

**Issue by viveleroi** [TheNodeILs/lodash-contrib#42]
Your implementation of camelCase doesn't create a lower-case first letter like lodash does, and I'm not seeing an easy to restore the original method.

**Comment by refack** [comment]
I'm removing it and three other redundant functions (`snakeCase` , `capitalize` and, `regexEscape`)

**Comment by viveleroi** [comment]
Thanks! I wasn't sure why you had some duplicates, I figured maybe you had them before lodash did.

**Comment by viveleroi** [comment]
Also, can you please tag a new version - we'll pull that into our app and remove some temporary code we had to solve this issue.

**Comment by refack** [comment]
Tagges
